/*
 */
package dev.amrv.sge.module.configuration;

import dev.amrv.sge.SGE;
import dev.amrv.sge.event.impl.SGEConfigurationChanged;
import dev.amrv.sge.window.SGENotifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerListModel;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author Adrian Martin Ruiz del Valle Aka. Ansuz
 */
public class ConfigurationPanel extends javax.swing.JPanel {

    private final List<LookAndFeelInfo> lafs = new ArrayList<>();
    private final DefaultComboBoxModel<LookAndFeelInfo> lafModel = new DefaultComboBoxModel();

    private final SGE sge;

    /**
     * Creates new form ConfigurationPanel
     *
     * @param sge
     */
    public ConfigurationPanel(SGE sge) {
        this.sge = sge;
        initComponents();
        comboBoxLookAndFeel.setRenderer(new LookAndFeelComboRenderer());
    }

    public synchronized void updateConfigFields() {
        lafModel.removeAllElements();

        for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            lafModel.addElement(info);
            if (UIManager.getLookAndFeel().getName().equals(info.getName()))
                lafModel.setSelectedItem(info);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLaF = new javax.swing.JLabel();
        comboBoxLookAndFeel = new javax.swing.JComboBox<>();
        buttonAccept = new javax.swing.JButton();

        labelLaF.setText("Look and feel");

        comboBoxLookAndFeel.setModel(lafModel);
        comboBoxLookAndFeel.setLightWeightPopupEnabled(false);

        buttonAccept.setText("Aceptar");
        buttonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLaF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonAccept))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLaF)
                    .addComponent(comboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(buttonAccept)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcceptActionPerformed
        if (lafModel.getSelectedItem() instanceof LookAndFeelInfo)
            try {
            sge.setLookAndFeel((LookAndFeelInfo) lafModel.getSelectedItem());
        } catch (Exception ex) {
            SGENotifier.displayError(this, "Error de configuracion", "No se ha podido cambiar el diseño de la interfaz", ex);
        }
        sge.getEventSystem().queueEvent(new SGEConfigurationChanged());
    }//GEN-LAST:event_buttonAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccept;
    private javax.swing.JComboBox<LookAndFeelInfo> comboBoxLookAndFeel;
    private javax.swing.JLabel labelLaF;
    // End of variables declaration//GEN-END:variables
}
