/*
 */
package dev.amrv.sge.module.providers;

import dev.amrv.sge.SGE;
import dev.amrv.sge.bbdd.DatabaseErrors;
import dev.amrv.sge.window.SGENotifier;
import java.sql.SQLException;
import java.util.Map;
import javax.swing.JPopupMenu;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;

/**
 *
 * @author Adrian Martin Ruiz del Valle Aka. Ansuz
 */
public class ProvidersPanel extends javax.swing.JPanel implements PopupMenuListener {

    private static final String BUTTON_MODIFY_EXISTING = "Modificar";
    private static final String BUTTON_MODIFY_NEW = "Crear";

    private final ProviderTableModel tableModel;
    private ProviderBuilder providerBuilder = new ProviderBuilder();
    private final SGE sge;
    private final JPopupMenu popupMenu;

    public ProvidersPanel(SGE sge) {
        this.sge = sge;
        this.tableModel = new ProviderTableModel(jTable1);
        jTable1.setColumnSelectionAllowed(false);
        popupMenu = createPopupMenu();
        initComponents();
    }

    private JPopupMenu createPopupMenu() {
        JPopupMenu menu = new JPopupMenu();
        menu.add(menuModifyProduct);
        menu.add(menuUpdateTable);
        menu.add(menuDeleteProduct);
        menu.addPopupMenuListener(this);
        return menu;
    }

    public void setProvider(ProviderBuilder builder) {
        providerBuilder = builder;
        fieldProviderName.setText(builder.name);
        fieldProviderCif.setText(builder.cif);
        fieldProviderReference.setText(builder.reference);

        fieldProviderMail.setText(builder.mail);
        fieldProviderPhone.setText(builder.phone);
        fieldProviderPhone2.setText(builder.phone2);

        fieldProviderAddress.setText(builder.address);
        fieldProviderPostalCode.setText(builder.postalCode);
        fieldProviderLocation.setText(builder.location);
        fieldProviderProvince.setText(builder.province);

        fieldProviderCif.setEnabled(!builder.exists());
        buttonUpdate.setText(builder.exists() ? BUTTON_MODIFY_EXISTING : BUTTON_MODIFY_NEW);
    }

    public ProviderBuilder getProvider() {
        return providerBuilder;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelProviderSee = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        buttonUpdateTable = new javax.swing.JButton();
        panelProviderModify = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldProviderName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldProviderReference = new javax.swing.JTextField();
        buttonUpdate = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        fieldProviderCif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelPhone = new javax.swing.JLabel();
        fieldProviderPhone = new javax.swing.JTextField();
        fieldProviderMail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        fieldProviderAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldProviderPostalCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldProviderLocation = new javax.swing.JTextField();
        fieldProviderProvince = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldProviderPhone2 = new javax.swing.JTextField();

        menuUpdateTable.setText("Actualizar");

        menuModifyProduct.setText("Modificar");
        menuModifyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModifyProductActionPerformed(evt);
            }
        });

        menuDeleteProduct.setText("Eliminar");
        menuDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteProductActionPerformed(evt);
            }
        });

        jTable1.setModel(tableModel);
        jTable1.setComponentPopupMenu(popupMenu);
        jTable1.setFocusable(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        buttonUpdateTable.setText("Actualizar");
        buttonUpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProviderSeeLayout = new javax.swing.GroupLayout(panelProviderSee);
        panelProviderSee.setLayout(panelProviderSeeLayout);
        panelProviderSeeLayout.setHorizontalGroup(
            panelProviderSeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProviderSeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProviderSeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addGroup(panelProviderSeeLayout.createSequentialGroup()
                        .addComponent(buttonUpdateTable)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelProviderSeeLayout.setVerticalGroup(
            panelProviderSeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProviderSeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonUpdateTable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedores", panelProviderSee);

        jLabel1.setText("Nombre");

        jLabel2.setText("Referencia");

        buttonUpdate.setText(BUTTON_MODIFY_NEW);
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonReset.setText("Resetear");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        jLabel3.setText("CIF");

        labelPhone.setText("Telefono");

        jLabel4.setText("Correo");

        jLabel5.setText("Direccion");

        jLabel6.setText("Codigo postal");

        jLabel7.setText("Localidad");

        jLabel8.setText("Provincia");

        javax.swing.GroupLayout panelProviderModifyLayout = new javax.swing.GroupLayout(panelProviderModify);
        panelProviderModify.setLayout(panelProviderModifyLayout);
        panelProviderModifyLayout.setHorizontalGroup(
            panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProviderModifyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(panelProviderModifyLayout.createSequentialGroup()
                        .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelProviderModifyLayout.createSequentialGroup()
                                    .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addComponent(fieldProviderName)
                                        .addComponent(jLabel2)
                                        .addComponent(fieldProviderReference, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldProviderCif, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)))
                                .addGroup(panelProviderModifyLayout.createSequentialGroup()
                                    .addComponent(buttonUpdate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonReset))
                                .addComponent(jSeparator1))
                            .addGroup(panelProviderModifyLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(220, 220, 220)
                                .addComponent(jLabel6))
                            .addGroup(panelProviderModifyLayout.createSequentialGroup()
                                .addComponent(fieldProviderAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldProviderPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProviderModifyLayout.createSequentialGroup()
                                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldProviderLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(fieldProviderProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelProviderModifyLayout.createSequentialGroup()
                                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldProviderPhone2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(fieldProviderPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPhone, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(fieldProviderMail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelProviderModifyLayout.setVerticalGroup(
            panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProviderModifyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldProviderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldProviderCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldProviderReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhone)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldProviderPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldProviderMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldProviderPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldProviderAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldProviderPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldProviderLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldProviderProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(panelProviderModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonReset))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear/Modificar", panelProviderModify);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        providerBuilder.name = fieldProviderName.getText().trim();
        providerBuilder.reference = fieldProviderReference.getText().trim();
        providerBuilder.cif = fieldProviderCif.getText().trim();

        providerBuilder.phone = fieldProviderPhone.getText().trim();
        providerBuilder.phone2 = fieldProviderPhone2.getText().trim();
        providerBuilder.mail = fieldProviderMail.getText().trim();

        providerBuilder.address = fieldProviderAddress.getText().trim();
        providerBuilder.postalCode = fieldProviderPostalCode.getText().trim();
        providerBuilder.location = fieldProviderLocation.getText().trim();
        providerBuilder.province = fieldProviderProvince.getText().trim();

        if (providerBuilder.isInvalid()) {
            SGENotifier.displayError(this, "Error", "La informacion no es valida");
            return;
        }

        try {
            final Provider provider = providerBuilder.generate(sge.getDatabase());
            final Map<String, ProviderAttribute> attributes = providerBuilder.generateAttributes(sge.getDatabase());

            tableModel.addProvider(provider, attributes);
        } catch (SQLException ex) {
            if (DatabaseErrors.alreadyExists(ex)) {
                sge.logger.error("Se ha intentado crear el proveedor {0} pero su cif {1} ya existe", providerBuilder.name, providerBuilder.cif);
                SGENotifier.displayError(this, "Error", "Ya existe un proveedor con la referencia " + providerBuilder.cif);
            } else {
                sge.logger.error(ex);
                SGENotifier.displayError(this, "Error", "No se ha podido actualizar la informacion del proveedor " + providerBuilder.name, ex);
            }
            return;
        }
        setProvider(new ProviderBuilder());
    }//GEN-LAST:event_buttonUpdateActionPerformed

    public void reloadProviders() {
        tableModel.clear();

        try {
            for (Provider provider : Provider.getAll(sge.getDatabase())) {
                tableModel.addProvider(provider, ProviderAttribute.getAll(sge.getDatabase(), provider));
            }
        } catch (SQLException ex) {
            sge.logger.error(ex);
        }

        jTable1.getSelectionModel().clearSelection();
        jTable1.invalidate();
        jTable1.repaint();
    }

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        setProvider(new ProviderBuilder());
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonUpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateTableActionPerformed
        reloadProviders();
    }//GEN-LAST:event_buttonUpdateTableActionPerformed

    private void menuModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModifyProductActionPerformed
        int row = tableModel.getPopupSelection();

        if (row == -1)
            return;

        final Provider provider = tableModel.getProviderAt(row);
        final Map<String, ProviderAttribute> attributes = tableModel.getAttributesAt(row);

        setProvider(new ProviderBuilder(provider, attributes));

        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_menuModifyProductActionPerformed

    private void menuDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteProductActionPerformed
        int row = tableModel.getPopupSelection();

        if (row == -1)
            return;

        final Provider provider = tableModel.getProviderAt(row);
        try {
            provider.delete(sge.getDatabase());
            sge.getDatabase().commit();
        } catch (SQLException ex) {
            sge.logger.error(ex);
        }
        tableModel.removeProvider(row);
    }//GEN-LAST:event_menuDeleteProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton buttonUpdateTable;
    private javax.swing.JTextField fieldProviderAddress;
    private javax.swing.JTextField fieldProviderCif;
    private javax.swing.JTextField fieldProviderLocation;
    private javax.swing.JTextField fieldProviderMail;
    private javax.swing.JTextField fieldProviderName;
    private javax.swing.JTextField fieldProviderPhone;
    private javax.swing.JTextField fieldProviderPhone2;
    private javax.swing.JTextField fieldProviderPostalCode;
    private javax.swing.JTextField fieldProviderProvince;
    private javax.swing.JTextField fieldProviderReference;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private final javax.swing.JTable jTable1 = new javax.swing.JTable();
    private javax.swing.JLabel labelPhone;
    private final javax.swing.JMenuItem menuDeleteProduct = new javax.swing.JMenuItem();
    private final javax.swing.JMenuItem menuModifyProduct = new javax.swing.JMenuItem();
    private final javax.swing.JMenuItem menuUpdateTable = new javax.swing.JMenuItem();
    private javax.swing.JPanel panelProviderModify;
    private javax.swing.JPanel panelProviderSee;
    // End of variables declaration//GEN-END:variables

    @Override
    public void popupMenuWillBecomeVisible(PopupMenuEvent e) {

    }

    @Override
    public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
        jTable1.clearSelection();
    }

    @Override
    public void popupMenuCanceled(PopupMenuEvent e) {
        jTable1.clearSelection();
    }
}
