/*
 */
package dev.amrv.sge.window;

import java.awt.Component;
import java.awt.datatransfer.StringSelection;
import java.io.PrintWriter;
import java.io.StringWriter;
import javax.swing.SwingUtilities;

/**
 *
 * @author Adrian Martin Ruiz del Valle Aka. Ansuz
 */
public class ExceptionDialog extends javax.swing.JDialog {

    /**
     * Creates new form ExceptionDialog
     */
    public ExceptionDialog(Component parent, String title, String message, Throwable exception) {
        super.setModal(true);
        initComponents();

        super.setTitle(title);
        textMessage.setText(message);

        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        exception.printStackTrace(pw);
        textError.setText(sw.toString());

        SwingUtilities.getRootPane(buttonAccept).setDefaultButton(buttonAccept);

        if (parent != null) {
            super.setLocationRelativeTo(parent);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textMessage = new javax.swing.JLabel();
        buttonAccept = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textError = new javax.swing.JTextArea();
        buttonCopy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textMessage.setText(" ");
        textMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonAccept.setText("Aceptar");
        buttonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcceptActionPerformed(evt);
            }
        });

        textError.setColumns(20);
        textError.setLineWrap(true);
        textError.setRows(5);
        textError.setEnabled(false);
        textError.setFocusable(false);
        jScrollPane1.setViewportView(textError);

        buttonCopy.setText("Copiar error");
        buttonCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCopyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAccept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCopy)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAccept)
                    .addComponent(buttonCopy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCopyActionPerformed
        final StringSelection content = new StringSelection(textError.getText());
        getToolkit().getSystemClipboard().setContents(content, content);
    }//GEN-LAST:event_buttonCopyActionPerformed

    private void buttonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcceptActionPerformed
        super.setVisible(false);
    }//GEN-LAST:event_buttonAcceptActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccept;
    private javax.swing.JButton buttonCopy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textError;
    private javax.swing.JLabel textMessage;
    // End of variables declaration//GEN-END:variables
}
