/*
 */
package dev.amrv.sge.window;

import java.awt.Component;

/**
 *
 * @author Adrian Martin Ruiz del Valle Aka. Ansuz
 */
public class LoadingDialog extends javax.swing.JDialog {

    private final Runnable onComplete;

    /**
     * Creates new form LoadingDialog
     *
     * @param parent
     * @param title
     * @param message
     * @param max
     * @param onComplete
     */
    public LoadingDialog(Component parent, String title, String message, int max, Runnable onComplete) {
        initComponents();
        super.setLocationRelativeTo(parent);
        super.setTitle(title);
        jLabel1.setText(title);
        jProgressBar1.setMaximum(max);
        this.onComplete = onComplete;
    }

    public void increase() {
        increase(1);
    }

    public void increase(int amount) {
        jProgressBar1.setValue(jProgressBar1.getValue() + amount);
        if (jProgressBar1.getValue() >= jProgressBar1.getMaximum())
            complete();
    }

    public void complete() {
        this.setVisible(false);
        if (onComplete != null)
            onComplete.run();
    }
    
    public void abort() {
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jProgressBar1.setMaximumSize(new java.awt.Dimension(32767, 17));
        jProgressBar1.setMinimumSize(new java.awt.Dimension(10, 17));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(146, 17));

        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
