/*
 */
package dev.amrv.sge.window;

import dev.amrv.sge.SGE;
import dev.amrv.sge.event.impl.SGEUserChangeEvent;
import dev.amrv.sge.module.Module;
import dev.amrv.sge.window.component.ModuleButton;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;

/**
 *
 * @author Adrian Martin Ruiz del Valle Aka. Ansuz
 */
public class SGEWindow extends javax.swing.JFrame {

    public static final String PROPERTY_WINDOW_WIDTH = "sge.window.width";
    public static final String PROPERTY_WINDOW_HEIGHT = "sge.window.height";
    public static final String PROPERTY_WINDOW_CENTER_X = "sge.window.center.x";
    public static final String PROPERTY_WINDOW_CENTER_Y = "sge.window.center.y";
    public static final String PROPERTY_WINDOW_STATE = "sge.window.state";

    /**
     * Creates new form SGEWindow
     */
    private final ButtonGroup moduleButtons = new ButtonGroup();
    private final SGE sge;

    public SGEWindow(SGE sge) {
        this.sge = sge;
        initComponents();

        int width = (int) getVariable(PROPERTY_WINDOW_WIDTH, super.getWidth());
        int height = (int) getVariable(PROPERTY_WINDOW_HEIGHT, super.getHeight());
        int centerX = (int) getVariable(PROPERTY_WINDOW_CENTER_X, 0);
        int centerY = (int) getVariable(PROPERTY_WINDOW_CENTER_Y, 0);
        int windowState = (int) getVariable(PROPERTY_WINDOW_STATE, super.getExtendedState());

        super.setExtendedState(windowState);
        super.setSize(width, height);
        super.setLocation(centerX, centerY);

        sge.getEventSystem().addListener(SGEUserChangeEvent.class, this::userChangeEvent);
        super.setTitle("SGE: " + sge.getUser().getUsername());
    }

    private double getVariable(String key, double defaultValue) {
        try {
            return Double.parseDouble(sge.getProperties().getProperty(key));
        } catch (NumberFormatException nfe) {
            sge.logger.warn("Can't get integer for property {0} {1}", key, nfe);
        }
        return defaultValue;
    }

    private void userChangeEvent(SGEUserChangeEvent event) {
        Enumeration<AbstractButton> buttonEnum = moduleButtons.getElements();

        while (buttonEnum.hasMoreElements()) {
            ModuleButton button = (ModuleButton) buttonEnum.nextElement();

            button.setEnabled(event.getNewUser().hasPermission(button.getModule().requirePermission()));
        }

        super.setTitle("SGE: " + event.getNewUser().getUsername());
    }

    public void addModule(Module module) {
        ModuleButton button = new ModuleButton(module);

        Dimension size = button.getMaximumSize();
        size.setSize(Integer.MAX_VALUE, size.getHeight());
        button.setMaximumSize(size);

        moduleButtons.add(button);
        button.setFocusable(false);

        button.addActionListener(a -> {
            sge.setModuleOnDisplay(module);
            moduleButtons.clearSelection();
        });

        button.setEnabled(sge.getUser().hasPermission(button.getModule().requirePermission()));
        panelModuleSelector.add(button, BorderLayout.CENTER);
    }

    public void setActivePanel(JPanel panel) {
        panelModuleViewer.removeAll();
        panelModuleViewer.add(panel);
        panelModuleViewer.revalidate();
        panelModuleViewer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelLeft = new javax.swing.JPanel();
        panelModuleSelector = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        panelModuleViewerScroll = new javax.swing.JScrollPane();
        panelModuleViewer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jSplitPane1.setDividerLocation(240);

        panelModuleSelector.setLayout(new javax.swing.BoxLayout(panelModuleSelector, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModuleSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModuleSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(panelLeft);

        panelModuleViewer.setLayout(new java.awt.BorderLayout());
        panelModuleViewerScroll.setViewportView(panelModuleViewer);

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModuleViewerScroll, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModuleViewerScroll, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jSplitPane1.setRightComponent(panelRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sge.logger.info("Saving window state");
        sge.getProperties().setProperty(PROPERTY_WINDOW_WIDTH, this.getWidth() + "");
        sge.getProperties().setProperty(PROPERTY_WINDOW_HEIGHT, this.getHeight() + "");
        sge.getProperties().setProperty(PROPERTY_WINDOW_CENTER_X, this.getLocation().x + "");
        sge.getProperties().setProperty(PROPERTY_WINDOW_CENTER_Y, this.getLocation().y + "");
        sge.getProperties().setProperty(PROPERTY_WINDOW_STATE, this.getExtendedState() + "");
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelModuleSelector;
    private javax.swing.JPanel panelModuleViewer;
    private javax.swing.JScrollPane panelModuleViewerScroll;
    private javax.swing.JPanel panelRight;
    // End of variables declaration//GEN-END:variables
}
