/*
 */
package dev.amrv.sge.module.database;

import dev.amrv.sge.module.DatabaseModule;
import java.awt.event.ActionEvent;
import java.sql.SQLException;

/**
 *
 * @author Adrian Martin Ruiz del Valle Aka. Ansuz
 */
public class DatabasePanel extends javax.swing.JPanel {

    private final DatabaseModule module;

    public DatabasePanel(DatabaseModule module) {
        this.module = module;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textConsole = new javax.swing.JTextArea();
        buttonExecute = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textInput = new javax.swing.JTextArea();
        buttonCommit = new javax.swing.JButton();
        buttonRollback = new javax.swing.JButton();

        textConsole.setColumns(20);
        textConsole.setRows(5);
        textConsole.setFocusable(false);
        jScrollPane1.setViewportView(textConsole);

        buttonExecute.setText("Execute query");
        buttonExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExecuteActionPerformed(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        textInput.setColumns(20);
        textInput.setRows(5);
        jScrollPane2.setViewportView(textInput);

        buttonCommit.setText("Commit");
        buttonCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCommitActionPerformed(evt);
            }
        });

        buttonRollback.setText("Rollback");
        buttonRollback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRollbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonExecute)
                    .addComponent(buttonClear)
                    .addComponent(buttonCommit)
                    .addComponent(buttonRollback))
                .addGap(64, 64, 64))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonExecute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCommit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRollback)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        clearText();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExecuteActionPerformed
        if ((evt.getModifiers() & ActionEvent.SHIFT_MASK) == ActionEvent.SHIFT_MASK)
            clearText();

        try {
            appendText(">> " + textInput.getText());
            appendText(module.executeQuery(textInput.getText()).toString());
        } catch (SQLException ex) {
            appendText(ex.getCause().toString());
            module.getSge().logger.error(ex);
        }

        if ((evt.getModifiers() & ActionEvent.CTRL_MASK) == ActionEvent.CTRL_MASK)
            textInput.setText("");
    }//GEN-LAST:event_buttonExecuteActionPerformed

    public void setCommand(String command) {
        textInput.setText(command);
    }

    public String getCommand() {
        return textInput.getText();
    }

    private void buttonCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCommitActionPerformed
        try {
            module.commit();
        } catch (SQLException ex) {
            appendText(ex.getCause().toString());
            module.getSge().logger.error(ex);
        }
    }//GEN-LAST:event_buttonCommitActionPerformed

    private void buttonRollbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRollbackActionPerformed
        try {
            module.rollback();
        } catch (SQLException ex) {
            appendText(ex.getCause().toString());
            module.getSge().logger.error(ex);
        }
    }//GEN-LAST:event_buttonRollbackActionPerformed

    public void appendText(String text) {
        textConsole.setText(textConsole.getText() + text + System.lineSeparator());
    }

    public void clearText() {
        textConsole.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonCommit;
    private javax.swing.JButton buttonExecute;
    private javax.swing.JButton buttonRollback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textConsole;
    private javax.swing.JTextArea textInput;
    // End of variables declaration//GEN-END:variables
}
