/*
 */
package dev.amrv.sge.module.users;

import dev.amrv.sge.SGE;
import dev.amrv.sge.auth.UserCredentials;
import dev.amrv.sge.event.impl.SGEUserChangeEvent;
import dev.amrv.sge.window.SGENotifier;
import dev.amrv.sge.window.UserCredentialsDialog;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adrian Martin Ruiz del Valle Aka. Ansuz
 */
public class UsersPanel extends javax.swing.JPanel {

    private final SGE sge;

    public UsersPanel(SGE sge) {
        this.sge = sge;
        initComponents();
        labelUsername.setText(sge.getUser().getUsername());
        sge.getEventSystem().addListener(SGEUserChangeEvent.class, this::onUserChange);
    }

    private void onUserChange(SGEUserChangeEvent event) {
        labelUsername.setText(event.getNewUser().getUsername());
        fieldPassword.setText("");
        fieldPasswordConfirm.setText("");
        fieldUsername.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        fieldPasswordConfirm = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldPermName = new javax.swing.JTextField();
        buttonGivePerm = new javax.swing.JButton();
        buttonNegatePerm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Nuevo nombre");

        jButton1.setText("Modificar usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nueva clave");

        jLabel3.setText("Clave actual");

        jLabel4.setText("Permiso");

        buttonGivePerm.setText("Otorgar");
        buttonGivePerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGivePermActionPerformed(evt);
            }
        });

        buttonNegatePerm.setText("Negar");
        buttonNegatePerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNegatePermActionPerformed(evt);
            }
        });

        jButton2.setText("Cambiar usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldPermName, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGivePerm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNegatePerm))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(23, 23, 23)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPermName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGivePerm)
                    .addComponent(buttonNegatePerm))
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = fieldUsername.getText();
        String password = new String(fieldPassword.getPassword());
        String passwordConfirm = new String(fieldPasswordConfirm.getPassword());

        if (password.trim().isEmpty())
            password = passwordConfirm;

        try {
            if (!UserCredentials.changeUsername(sge, username, password, passwordConfirm)) {
                fieldPassword.setText("");
                SGENotifier.displayError(this, "Error", "Password is not correct");
            }
        } catch (IOException ex) {
            SGENotifier.displayError(this, "Error", "Error changing user", ex);
            sge.logger.error(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    protected boolean requireElevatedAccess() {
        UserCredentials elevatedUser = UserCredentialsDialog.requestUser(this);

        try {
            elevatedUser.loadPermissions();
        } catch (IOException ex) {
            SGENotifier.displayError(this, "Error", "Error loading permissions for elevated access");
            return false;
        }

        return elevatedUser.hasPermission("users.modify") || elevatedUser.hasPermission("administrator");
    }

    private void buttonGivePermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGivePermActionPerformed
        if (requireElevatedAccess()) {
            sge.getUser().getPermissions().setPermission(fieldPermName.getText().trim(), true);
        } else {
            SGENotifier.displayError(this, "Error de acceso", "No puedes realizar esta accion");
        }
    }//GEN-LAST:event_buttonGivePermActionPerformed

    private void buttonNegatePermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNegatePermActionPerformed
        if (requireElevatedAccess()) {
            sge.getUser().getPermissions().setPermission(fieldPermName.getText().trim(), false);
        } else {
            SGENotifier.displayError(this, "Error de acceso", "No puedes realizar esta accion");
        }
    }//GEN-LAST:event_buttonNegatePermActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sge.setUser(UserCredentialsDialog.requestUser(this));
    }//GEN-LAST:event_jButton2ActionPerformed

    public synchronized void changeUser() {
        fieldUsername.setText(sge.getUser().getUsername());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGivePerm;
    private javax.swing.JButton buttonNegatePerm;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPasswordField fieldPasswordConfirm;
    private javax.swing.JTextField fieldPermName;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
